### ISSUE TITLE
HTML5 void elements not parsed correctly

### ISSUE THREAD

**Issue by digitalcora** [twilson63/html2haml#17]
This input:

```
<hr>
<h2>
  First line of my header<br>
  <%= some_helper %> and second header line
</h2>
```

Results in this output:

```
%hr
  %h2
    First line of my header
    %br
      = some_helper
      and second header line
```

However, `<hr>` and `<br>` can never have any contents. Maybe upstream bug? I note html2haml has released two new beta versions beyond your current one, though I can't seem to get it working at the moment to check (complains about missing hpricot even though it's installed).

**Comment by twilson63** [comment]
Hey Alex,

Thanks for reporting, I will take a look and update to the most recent beta
version and see if that resolves the issue.

Thanks

Tom

On Thu, Feb 7, 2013 at 11:36 AM, Alex Grant notifications@github.comwrote:

> This input:
> 
> <hr>
> 
> <h2>
>   First line of my header<br>
>   <%= some_helper %> and second header line
> </h2>
> 
> Results in this output:
> 
> %hr
>   %h2
>     First line of my header
>     %br
>       = some_helper
>       and second header line
> 
> However, <hr> and <br> can never have any contents. Maybe upstream bug? I
> note html2haml has released two new beta versions beyond your current one,
> though I can't seem to get it working at the moment to check (complains
> about missing hpricot even though it's installed).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/twilson63/html2haml/issues/17.

## 

Tom Wilson
Jack Russell Software Company Division of CareKinesis
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-881-2171
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_Yorkhttp://www.jackhq.com/calendar

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.

**Comment by twilson63** [comment]
Hey Alex,

This should be fixed.

``` ruby

Haml::HTML.new(html, :erb => true, :xhtml => false).render
```

I disabled the xhtml requirement.

Thanks

Tom
